using System.Collections;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bukmacher
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Bukmacher")]
	public partial class LinqToSql_DB_BukmacherDataContext : System.Data.Linq.DataContext, IEnumerable<object>
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMatch(Match instance);
    partial void UpdateMatch(Match instance);
    partial void DeleteMatch(Match instance);
    #endregion
		
		public LinqToSql_DB_BukmacherDataContext() : 
				base(global::Bukmacher.Properties.Settings.Default.DB_BukmacherConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSql_DB_BukmacherDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSql_DB_BukmacherDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSql_DB_BukmacherDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSql_DB_BukmacherDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Match> Matches
		{
			get
			{
				return this.GetTable<Match>();
			}
		}

	    public IEnumerator<object> GetEnumerator()
	    {
	        throw new NotImplementedException();
	    }

	    IEnumerator IEnumerable.GetEnumerator()
	    {
	        return GetEnumerator();
	    }
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Matches")]
	public partial class Match : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Sport;
		
		private string _Team1;
		
		private string _Team2;
		
		private double @__1;
		
		private double _X;
		
		private double @__2;
		
		private System.DateTime _Data_spotkania;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSportChanging(string value);
    partial void OnSportChanged();
    partial void OnTeam1Changing(string value);
    partial void OnTeam1Changed();
    partial void OnTeam2Changing(string value);
    partial void OnTeam2Changed();
    partial void On_1Changing(double value);
    partial void On_1Changed();
    partial void OnXChanging(double value);
    partial void OnXChanged();
    partial void On_2Changing(double value);
    partial void On_2Changed();
    partial void OnData_spotkaniaChanging(System.DateTime value);
    partial void OnData_spotkaniaChanged();
    #endregion
		
		public Match()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sport", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Sport
		{
			get
			{
				return this._Sport;
			}
			set
			{
				if ((this._Sport != value))
				{
					this.OnSportChanging(value);
					this.SendPropertyChanging();
					this._Sport = value;
					this.SendPropertyChanged("Sport");
					this.OnSportChanged();
  
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Team1
		{
			get
			{
				return this._Team1;
			}
			set
			{
				if ((this._Team1 != value))
				{
					this.OnTeam1Changing(value);
					this.SendPropertyChanging();
					this._Team1 = value;
					this.SendPropertyChanged("Team1");
					this.OnTeam1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Team2
		{
			get
			{
				return this._Team2;
			}
			set
			{
				if ((this._Team2 != value))
				{
					this.OnTeam2Changing(value);
					this.SendPropertyChanging();
					this._Team2 = value;
					this.SendPropertyChanged("Team2");
					this.OnTeam2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Float NOT NULL")]
		public double _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.On_1Changing(value);
					this.SendPropertyChanging();
					this.@__1 = value;
					this.SendPropertyChanged("_1");
					this.On_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X", DbType="Float NOT NULL")]
		public double X
		{
			get
			{
				return this._X;
			}
			set
			{
				if ((this._X != value))
				{
					this.OnXChanging(value);
					this.SendPropertyChanging();
					this._X = value;
					this.SendPropertyChanged("X");
					this.OnXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2]", Storage="__2", DbType="Float NOT NULL")]
		public double _2
		{
			get
			{
				return this.@__2;
			}
			set
			{
				if ((this.@__2 != value))
				{
					this.On_2Changing(value);
					this.SendPropertyChanging();
					this.@__2 = value;
					this.SendPropertyChanged("_2");
					this.On_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data spotkania]", Storage="_Data_spotkania", DbType="Date NOT NULL")]
		public System.DateTime Data_spotkania
		{
			get
			{
				return this._Data_spotkania;
			}
			set
			{
				if ((this._Data_spotkania != value))
				{
					this.OnData_spotkaniaChanging(value);
					this.SendPropertyChanging();
					this._Data_spotkania = value;
					this.SendPropertyChanged("Data_spotkania");
					this.OnData_spotkaniaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
